SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_SEL_ESPECIALIDADE] 
	(@PS_RETURN INT OUTPUT,
	@PS_MESSAGE VARCHAR(MAX) OUTPUT)AS
SET NOCOUNT ON;
DECLARE @ROWCOUNT INT
BEGIN TRY
	SELECT * FROM TABELA_ESPECIALIDADE
	SET @ROWCOUNT = @@ROWCOUNT
	SET @PS_RETURN = 0
	SET @PS_MESSAGE = '['+OBJECT_NAME(@@PROCID)+'] EXECUTADO COM SUCESSO. ' + CONVERT(VARCHAR(2), @ROWCOUNT) + ' ESPECIALIDADES RETORNADOS'
END TRY
BEGIN CATCH
	SET @PS_RETURN = ERROR_LINE()
	SET @PS_MESSAGE = '[' + OBJECT_NAME(@@PROCID) + '] ERRO, LINHA: ' + CONVERT(VARCHAR(5), ERROR_LINE()) + ' -- CODIGO: ' + CONVERT(VARCHAR(5), ERROR_NUMBER()) + ' -- ' + ERROR_MESSAGE();
END CATCH
GO
